base.url=https://www.saucedemo.com
valid.username=standard_user
valid.password=secret_sauce
invalid.username=invalid_user
invalid.password=invalid_pass
browser=chrome
headless=false
implicit.wait.seconds=0
explicit.wait.seconds=10
screenshot.dir=target/screenshots
