browser.name=CHROME
base.url=https://www.saucedemo.com/
standard.username=standard_user
standard.password=secret_sauce
locked.username=locked_out_user
locked.password=secret_sauce
invalid.username=ghost_user
invalid.password=ghost_password

wait.seconds=10

headless=false
implicit.wait.seconds=10
page.load.timeout.seconds=30
screenshot.on.failure=true

