site.url=https://demoqa.com
dynamic_site.path=/dynamic-properties
progress_bar.path=/progress-bar

# Wait Strategy Configs
IMPLICIT_WAIT_TIMEOUT_DURATION_SECONDS=10
EXPLICIT_WAIT_TIMEOUT_DURATION_SECONDS=10
DYNAMIC_WAIT_TIMEOUT_DURATION_SECONDS=20

FLUENT_WAIT_TIMEOUT_DURATION_SECONDS=10
FLUENT_WAIT_POLLING_DURATION_MILLIS=500
